# ===========================================================
# SpeakSecure — Authorization Code Repository
# Database operations for short-lived OAuth authorization codes.
#
# This is the OAuth 2.0 "authorization_code" grant, RFC 6749 §4.1.
#
# FLOW:
#   1. User completes voice verification on our /authorize page
#   2. We generate an authorization code, store it in this table with
#      the verification result (user_id, verified, similarity_score),
#      the redirect_uri that was used, and an expiry 10 seconds in
#      the future.
#   3. We redirect the browser back to the integrator's callback URL
#      with the code in the query string: ?code=xyz&state=abc
#   4. The integrator's BACKEND (not their frontend!) calls our
#      POST /token endpoint, authenticated with their API key,
#      sending the code and the redirect_uri.
#   5. We look up the code, verify it's still valid, hasn't been
#      consumed, belongs to the same API key AND the same redirect_uri,
#      and return the verification result.
#   6. The code is marked consumed — single-use.
#
# WHY EXACT redirect_uri MATCH ON EXCHANGE?
#   This binds the code to the URL it was created for. Even if an
#   attacker somehow obtains the code (e.g. via referer leak), they
#   can't exchange it without knowing AND being authorised for the
#   exact same redirect_uri the legitimate flow used.
# ===========================================================

from datetime import datetime, UTC
from typing import Optional

from Storage.database import get_connection


class AuthorizationCodeRepository:
    """Database-backed storage for OAuth authorization codes."""

    def create(
        self,
        code: str,
        user_id: str,
        verified: bool,
        api_key_id: int,
        redirect_uri: str,
        similarity_score: Optional[float],
        decision: str,
        expires_at: str,
    ) -> int:
        """
        Insert a new authorization code record.

        Args:
            code: The random code string (generated by the OAuth service)
            user_id: Which user was being verified
            verified: Whether the verification succeeded
            api_key_id: Which API key initiated the /authorize call
            redirect_uri: The exact redirect_uri used during /authorize.
                          Must match again at /token exchange.
            similarity_score: The voice match score, or None if no match
            decision: "accepted" / "rejected" / "retry"
            expires_at: ISO datetime string when the code expires (10s)

        Returns:
            The database ID of the new code record.
        """
        now = datetime.now(UTC).isoformat()

        with get_connection() as conn:
            cursor = conn.execute(
                """
                INSERT INTO authorization_codes
                    (code, user_id, verified, api_key_id, redirect_uri,
                     similarity_score, decision, created_at, expires_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    code,
                    user_id,
                    1 if verified else 0,
                    api_key_id,
                    redirect_uri,
                    similarity_score,
                    decision,
                    now,
                    expires_at,
                ),
            )
            return cursor.lastrowid

    def exchange(self, code: str, api_key_id: int, redirect_uri: str) -> Optional[dict]:
        """
        Atomically look up and mark an authorization code as consumed.

        Returns the code record (as dict) if it was valid, unconsumed,
        not expired, AND belonged to the same API key + redirect_uri
        that the integrator is now requesting. Returns None otherwise.

        This is the CORE security check of the OAuth flow. We require
        ALL of these to pass before returning the user identity:

        - code must exist            → prevents forged codes
        - must not be consumed       → prevents replay
        - must not be expired        → prevents stale codes being leaked
        - api_key_id must match      → prevents cross-integrator theft
        - redirect_uri must match    → binds code to its original URL

        Atomic: the SELECT and UPDATE share a single connection and
        therefore a single SQLite transaction. Two concurrent /token
        calls cannot both consume the same code — the second one will
        see consumed_at already set.
        """
        now = datetime.now(UTC).isoformat()

        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT id, code, user_id, verified, api_key_id, redirect_uri,
                       similarity_score, decision, created_at, expires_at,
                       consumed_at
                FROM authorization_codes
                WHERE code = ?
                  AND consumed_at IS NULL
                  AND expires_at > ?
                  AND api_key_id = ?
                  AND redirect_uri = ?
                """,
                (code, now, api_key_id, redirect_uri),
            ).fetchone()

            if row is None:
                return None

            # Belt-and-braces UPDATE — handles the very rare race where
            # another request consumed the code between our SELECT and
            # this UPDATE (extremely unlikely with one connection but safe).
            cursor = conn.execute(
                """
                UPDATE authorization_codes
                SET consumed_at = ?
                WHERE id = ? AND consumed_at IS NULL
                """,
                (now, row["id"]),
            )

            if cursor.rowcount != 1:
                return None

            return {
                "id": row["id"],
                "code": row["code"],
                "user_id": row["user_id"],
                "verified": bool(row["verified"]),
                "api_key_id": row["api_key_id"],
                "redirect_uri": row["redirect_uri"],
                "similarity_score": row["similarity_score"],
                "decision": row["decision"],
                "created_at": row["created_at"],
                "expires_at": row["expires_at"],
                "consumed_at": now,
            }

    def cleanup_expired(self) -> int:
        """
        Delete authorization codes that have expired.
        Called periodically by the background cleanup scheduler so the
        table doesn't grow unbounded. Expired codes are never valid,
        so deleting them has no functional impact.

        Returns the number of rows deleted.
        """
        now = datetime.now(UTC).isoformat()

        with get_connection() as conn:
            cursor = conn.execute(
                "DELETE FROM authorization_codes WHERE expires_at < ?",
                (now,),
            )
            return cursor.rowcount